### ISSUE TITLE
Please consider tagging releases

### ISSUE THREAD

**Issue by steinex** [amir/sctd#1]
Hi,

i'd like to package this for Void Linux. It's policy is to only allow packages with proper releases for inclusion, though.

So may I kindly ask you to tag releases, please?

Thanks!

**Comment by amir** [comment]
Hi,

Thanks for filing this issue. I meant to setup a proper github workflow to automate the release process but need to investigate it first since I've never used github workflows before. But for you, in order to package it, do you need aretfacts to be published and attached to releases or just a mere git tag would suffice?

**Comment by steinex** [comment]
A normal GitHub release would be sufficient. (`Releases -> "Create a new release"`). This will automatically create a git tag and a downloadable tarball.

Besides this, to be able to package it, sctd would need a LICENSE. Can you consider adding one before doing a release? If you want, I can open a separate issue for that.

**Comment by amir** [comment]
Thanks for clarification. I released a version and added LICENSE file.

**Comment by steinex** [comment]
Nice, thanks! :+1: 

I was looking for something like sctd for a while now, glad you did it! I'll go ahead now and prepare a package for Void.
